// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"hotel/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/hotel/api/index",
				Handler: IndexHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/hotel/api/checkIn",
				Handler: CheckInHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/hotel/api/complete",
				Handler: CompleteHandler(serverCtx),
			},
		},
	)
}
